# Generates en_hi_extra.json from a dict. Run: python make_hi_extra.py
# Add more entries to EXTRA below and re-run to update en_hi_extra.json
import json, os
BASE = os.path.dirname(os.path.abspath(__file__))
EXTRA = {
    "bob": "बॉब", "division": "विभाजन", "divorce": "तलाक", "dna": "डीएनए", "doc": "डॉक्टर",
    "dock": "गोदी", "document": "दस्तावेज़", "dolly": "गुड़िया", "dolphin": "डॉल्फिन", "dome": "गुंबद",
    "donkey": "गधा", "donna": "डोना", "doorbell": "घंटी", "dorm": "छात्रावास", "dose": "खुराक",
    "dot": "बिंदु", "double": "दोगुना", "dough": "आटा", "dove": "कबूतर", "down": "नीचे",
    "draft": "मसौदा", "drain": "नाली", "drake": "ड्रेक", "drama": "नाटक", "drawing": "चित्र",
    "dread": "डर", "dresser": "ड्रेसर", "dressing": "पट्टी", "drift": "बहाव", "drill": "ड्रिल",
    "drinking": "पीना", "drum": "ढोल", "duck": "बत्तख", "dude": "यार", "duke": "ड्यूक",
    "dump": "ढेर", "dune": "टिब्बा", "dusk": "शाम", "dwarf": "बौना", "eagle": "चील",
    "earl": "अर्ल", "earring": "कान की बाली", "earthquake": "भूकंप", "ease": "आराम",
    "easter": "ईस्टर", "eating": "खाना", "eave": "ओलती", "echo": "प्रतिध्वनि", "economy": "अर्थव्यवस्था",
    "edition": "संस्करण", "education": "शिक्षा", "ego": "अहंकार", "elder": "बुजुर्ग",
    "election": "चुनाव", "electricity": "बिजली", "element": "तत्व", "elephant": "हाथी",
    "elf": "एल्फ", "email": "ईमेल", "embarrassment": "शर्मिंदगी", "embassy": "दूतावास",
    "embrace": "आलिंगन", "emerald": "पन्ना", "emperor": "सम्राट", "empire": "साम्राज्य",
    "employee": "कर्मचारी", "employer": "नियोक्ता", "emptiness": "खालीपन", "encounter": "मुठभेड़",
    "ending": "अंत", "engagement": "सगाई", "engineer": "इंजीनियर", "engineering": "इंजीनियरिंग",
    "enterprise": "उद्यम", "entertainment": "मनोरंजन", "enthusiasm": "उत्साह", "entity": "इकाई",
    "entry": "प्रवेश", "environment": "पर्यावरण", "episode": "एपिसोड", "era": "युग",
    "errand": "काम", "error": "गलती", "escape": "भागना", "escort": "संरक्षक", "essay": "निबंध",
    "essence": "सार", "estate": "संपत्ति", "eternity": "अनंत काल", "eve": "पूर्व संध्या",
    "evil": "बुराई", "exam": "परीक्षा", "examination": "जांच", "example": "उदाहरण",
    "exception": "अपवाद", "exchange": "विनिमय", "excuse": "बहाना", "executive": "कार्यकारी",
    "exercise": "व्यायाम", "exhaustion": "थकान", "existence": "अस्तित्व", "exit": "निकास",
    "expanse": "विस्तार", "expectation": "उम्मीद", "expedition": "अभियान", "expense": "खर्च",
    "expert": "विशेषज्ञ", "explanation": "व्याख्या", "explosion": "विस्फोट", "extension": "विस्तार",
    "extent": "सीमा", "eyelid": "पलक", "fabric": "कपड़ा", "facility": "सुविधा", "factor": "कारक",
    "factory": "कारखाना", "faculty": "संकाय", "failure": "विफलता", "fairy": "परी",
    "fame": "प्रसिद्धि", "fang": "विषदंत", "fantasy": "कल्पना", "farewell": "विदाई",
    "farmer": "किसान", "farmhouse": "खेत का घर", "fashion": "फैशन", "fat": "चर्बी",
    "fatigue": "थकान", "favor": "पक्ष", "favorite": "पसंदीदा", "feast": "दावत",
    "feather": "पंख", "fee": "शुल्क", "feed": "चारा", "feel": "अनुभव", "fella": "आदमी",
    "female": "महिला", "ferry": "नौका", "festival": "त्योहार", "fever": "बुखार",
    "fiction": "कल्पना", "fighter": "योद्धा", "fighting": "लड़ाई", "fingernail": "नाखून",
    "fingertip": "उंगली का सिरा", "finish": "समाप्ति", "fireplace": "अंगीठी", "firm": "फर्म",
    "fisherman": "मछुआरा", "fishing": "मछली पकड़ना", "fit": "फिट", "flag": "झंडा",
    "flake": "परत", "flannel": "फलालैन", "flap": "फ्लैप", "flare": "ज्वाला", "flashlight": "टॉर्च",
    "fleet": "बेड़ा", "flicker": "झिलमिलाहट", "float": "तैरना", "flock": "झुंड", "flood": "बाढ़",
    "flora": "वनस्पति", "flour": "आटा", "flow": "प्रवाह", "fluid": "तरल", "flute": "बांसुरी",
    "flying": "उड़ान", "foam": "झाग", "focus": "फोकस", "fog": "कोहरा", "fold": "तह",
    "folder": "फोल्डर", "football": "फुटबॉल", "footstep": "कदम", "ford": "नदी पार",
    "forearm": "प्रकोष्ठ", "forefinger": "तर्जनी", "foreigner": "विदेशी", "foreman": "फोरमैन",
    "fork": "कांटा", "formation": "गठन", "fort": "किला", "fortune": "भाग्य", "foundation": "नींव",
    "fountain": "फव्वारा", "fox": "लोमड़ी", "foyer": "प्रवेश कक्ष", "fraction": "भिन्न",
    "fragment": "टुकड़ा", "freak": "विचित्र", "freeway": "हाईवे", "freeze": "जमना",
    "freezer": "फ्रीजर", "french": "फ्रेंच", "freshman": "नए छात्र", "fridge": "फ्रिज",
    "friendship": "दोस्ती", "fringe": "किनारी", "frog": "मेंढक", "frost": "पाला",
    "frown": "भौंह चढ़ाना", "frustration": "निराशा", "fry": "तलना", "fuck": "भाड़ में",
    "fuel": "ईंधन", "function": "कार्य", "fund": "निधि", "fury": "क्रोध",
    "galaxy": "आकाशगंगा", "gale": "तूफान", "gallery": "गैलरी", "gang": "गिरोह",
    "gap": "अंतर", "garbage": "कचरा", "garment": "कपड़ा", "gasp": "हांफना", "gathering": "जमाव",
    "gene": "जीन", "generator": "जनरेटर", "genius": "प्रतिभा", "gentry": "अभिजात वर्ग",
    "german": "जर्मन", "giant": "विशाल", "giggle": "किकियाना", "gin": "जिन",
    "ginger": "अदरक", "git": "गिट", "glare": "चमक", "glen": "घाटी", "glimpse": "झलक",
    "glint": "चमक", "globe": "ग्लोब", "gloom": "उदासी", "glory": "गौरव", "glow": "चमक",
    "goal": "लक्ष्य", "goat": "बकरी", "goblin": "गोबलिन", "goddess": "देवी", "goggle": "गॉगल",
    "golf": "गोल्फ", "good": "अच्छा", "goodness": "अच्छाई", "goose": "हंस", "gossip": "गपशप",
    "governor": "राज्यपाल", "gown": "गाउन", "graduate": "स्नातक", "graduation": "स्नातक",
    "grain": "अनाज", "grandchild": "पोता-पोती", "granddaughter": "पोती", "grandma": "दादी",
    "grandpa": "दादा", "grandparent": "दादा-दादी", "grandson": "पोता", "granite": "ग्रेनाइट",
    "granny": "दादी", "grape": "अंगूर", "grasp": "पकड़", "gratitude": "कृतज्ञता",
    "gravel": "बजरी", "graveyard": "कब्रिस्तान", "gravity": "गुरुत्व", "gray": "धूसर",
    "grease": "चिकनाई", "greek": "यूनानी", "greeting": "अभिवादन", "grief": "दुख",
    "grill": "ग्रिल", "groan": "कराह", "grocery": "किराना", "grove": "उपवन", "growl": "गुर्राना",
    "grownup": "वयस्क", "growth": "विकास", "grunt": "ग्रंट", "guardian": "संरक्षक",
    "guess": "अनुमान", "guide": "गाइड", "guilt": "दोष", "guitar": "गिटार", "gulf": "खाड़ी",
    "gum": "मसूड़ा", "gust": "झोंका", "gut": "आंत", "gym": "जिम", "gypsy": "जिप्सी",
    "haircut": "बाल कटवाना", "halt": "रुकना", "ham": "हैम", "hamburger": "हैमबर्गर",
    "hammer": "हथौड़ा", "handful": "मुट्ठी भर", "handkerchief": "रुमाल", "handle": "हत्था",
    "happiness": "खुशी", "harbor": "बंदरगाह", "hardware": "हार्डवेयर", "harm": "नुकसान",
    "harmony": "सामंजस्य", "harness": "काठी", "hatch": "हैच", "hatred": "नफरत",
    "haven": "शरण", "hawk": "बाज", "hay": "घास", "haze": "धुंध", "headache": "सिरदर्द",
    "headlight": "हेडलाइट", "headline": "सुर्ख़ी", "headquarters": "मुख्यालय", "heap": "ढेर",
    "hearing": "सुनवाई", "heartbeat": "धड़कन", "hearth": "चूल्हा", "hedge": "बाड़",
    "heir": "वारिस", "helicopter": "हेलीकॉप्टर", "hem": "हैम", "hen": "मुर्गी",
    "herb": "जड़ी बूटी", "herd": "झुंड", "hesitation": "संकोच", "hide": "छिपाना",
    "hillside": "पहाड़ी", "hinge": "कब्जा", "hint": "संकेत", "hiss": "सीटी",
    "hit": "मार", "holder": "धारक", "holiday": "छुट्टी", "hollow": "खोखला",
    "holly": "होली", "holster": "होल्स्टर", "homer": "होमर", "homework": "गृहकार्य",
    "homicide": "हत्या", "hood": "हुड", "hoof": "खुर", "hook": "हुक", "hop": "कूद",
    "hose": "पाइप", "host": "मेजबान", "hostage": "बंधक", "hound": "शिकारी कुत्ता",
    "household": "परिवार", "howl": "चीख", "hue": "रंग", "hug": "गले लगाना",
    "hull": "पतवार", "hum": "गुनगुनाना", "humanity": "मानवता", "humor": "हास्य",
    "hunger": "भूख", "hunt": "शिकार", "hunter": "शिकारी", "hunting": "शिकार",
    "hurricane": "तूफान", "hurry": "जल्दी", "hut": "झोपड़ी", "identity": "पहचान",
    "idiot": "मूर्ख", "ignorance": "अज्ञान", "illness": "बीमारी", "illusion": "भ्रम",
    "illustration": "चित्रण", "imagination": "कल्पना", "imitation": "नकल",
    "impact": "प्रभाव", "implication": "निहितार्थ", "importance": "महत्व",
    "impression": "छाप", "impulse": "आवेग", "incident": "घटना", "income": "आय",
    "independence": "स्वतंत्रता", "index": "सूचकांक", "indian": "भारतीय",
    "indication": "संकेत", "individual": "व्यक्ति", "industry": "उद्योग", "infant": "शिशु",
    "influence": "प्रभाव", "injury": "चोट", "ink": "स्याही", "inn": "सराय",
    "innocence": "मासूमियत", "inquiry": "पूछताछ", "insect": "कीट", "inside": "अंदर",
    "insight": "अंतर्दृष्टि", "inspection": "निरीक्षण", "inspector": "निरीक्षक",
    "inspiration": "प्रेरणा", "instinct": "वृत्ति", "institute": "संस्थान",
    "institution": "संस्था", "instruction": "निर्देश", "instructor": "प्रशिक्षक",
    "instrument": "उपकरण", "insult": "अपमान", "insurance": "बीमा", "intelligence": "बुद्धि",
    "intensity": "तीव्रता", "intent": "इरादा", "intention": "मंशा", "intercom": "इंटरकॉम",
    "interior": "आंतरिक", "internet": "इंटरनेट", "interrupt": "रुकावट",
    "intersection": "चौराहा", "interval": "अंतराल", "interview": "साक्षात्कार",
    "intimacy": "अंतरंगता", "introduction": "परिचय", "intruder": "घुसपैठिया",
    "investigation": "जांच", "investigator": "जांचकर्ता", "investment": "निवेश",
    "invitation": "निमंत्रण", "iris": "आईरिस", "irony": "विडंबना", "irritation": "जलन",
    "italian": "इतालवी", "item": "आइटम", "ivory": "हाथी दांत", "ivy": "आइवी",
    "jail": "जेल", "jam": "जाम", "japanese": "जापानी", "jar": "जार", "jasmine": "चमेली",
    "jazz": "जैज़", "jealousy": "ईर्ष्या", "jeep": "जीप", "jelly": "जेली", "jerk": "झटका",
    "jersey": "जर्सी", "jet": "जेट", "jewel": "जवाहरात", "jewelry": "आभूषण",
    "joint": "जोड़", "journal": "पत्रिका", "journalist": "पत्रकार", "judgment": "निर्णय",
    "jug": "जग", "juice": "रस", "jump": "कूद", "jungle": "जंगल", "junk": "कबाड़",
    "jury": "जूरी", "kettle": "केतली", "keyboard": "कीबोर्ड", "kick": "लात",
    "killing": "हत्या", "kin": "रिश्तेदार", "kindness": "दया", "kingdom": "राज्य",
    "kip": "किप", "kit": "किट", "kitten": "बिल्ली का बच्चा", "kitty": "किटी",
    "knight": "नाइट", "knob": "नॉब", "knock": "दस्तक", "knot": "गांठ", "knuckle": "अंगुली का जोड़",
    "label": "लेबल", "laboratory": "प्रयोगशाला", "lace": "फीता", "lack": "कमी",
    "lad": "लड़का", "ladder": "सीढ़ी", "lamb": "मेमना", "lance": "भाला",
    "landing": "लैंडिंग", "landscape": "परिदृश्य", "lantern": "लालटेन", "laptop": "लैपटॉप",
    "laser": "लेजर", "lash": "चाबुक", "launch": "लॉन्च", "laundry": "कपड़े धोना",
    "laurel": "लॉरेल", "lava": "लावा", "lavender": "लैवेंडर", "layer": "परत",
    "lead": "सीसा", "league": "लीग", "leap": "छलांग", "learning": "सीखना", "leave": "छुट्टी",
    "lecture": "व्याख्यान", "ledge": "कगार", "left": "बाएं", "legend": "किंवदंती",
    "lemon": "नींबू", "lens": "लेंस", "liar": "झूठा", "liberty": "स्वतंत्रता",
    "license": "लाइसेंस", "lid": "ढक्कन", "lieutenant": "लेफ्टिनेंट", "lifetime": "जीवन",
    "lift": "लिफ्ट", "lighter": "लाइटर", "lighting": "रोशनी", "lightning": "बिजली",
    "lime": "चूना", "limit": "सीमा", "limo": "लिमो", "limp": "लंगड़ा", "linen": "लिनन",
    "link": "लिंक", "lion": "शेर", "lipstick": "लिपस्टिक", "liquid": "तरल",
    "liquor": "शराब", "literature": "साहित्य", "litter": "कूड़ा", "liver": "जिगर",
    "lizard": "छिपकली", "load": "भार", "loaf": "पाव", "loan": "कर्ज", "local": "स्थानीय",
    "location": "स्थान", "locker": "लॉकर", "lodge": "लॉज", "loft": "लॉफ्ट",
    "log": "लॉग", "logic": "तर्क", "logo": "लोगो", "loneliness": "अकेलापन",
    "longing": "तड़प", "loop": "लूप", "loser": "हारने वाला", "lounge": "लाउंज",
    "lovemaking": "संभोग", "loyalty": "निष्ठा", "luggage": "सामान", "lump": "गांठ",
    "lung": "फेफड़ा", "lust": "वासना", "luxury": "लक्जरी", "mac": "मैक",
    "machinery": "मशीनरी", "madam": "महोदया", "madame": "मैडम", "madness": "पागलपन",
    "mage": "जादूगर", "magician": "जादूगर", "maid": "नौकरानी", "mailbox": "डाकबॉक्स",
    "maintenance": "रखरखाव", "majesty": "महिमा", "major": "मेजर", "maker": "निर्माता",
    "makeup": "मेकअप", "male": "पुरुष", "mall": "मॉल", "management": "प्रबंधन",
    "manor": "मनोर", "mansion": "हवेली", "manuscript": "पांडुलिपि", "maple": "मेपल",
    "marble": "संगमरमर", "march": "मार्च", "mare": "घोड़ी", "marina": "मरीना",
    "marine": "समुद्री", "marker": "मार्कर", "marsh": "दलदल", "mason": "राजमिस्त्री",
    "mat": "चटाई", "mate": "साथी", "math": "गणित", "mattress": "गद्दा",
    "maverick": "मावेरिक", "mayor": "मेयर", "maze": "भूलभुलैया", "meadow": "घास का मैदान",
    "mean": "मतलब", "meantime": "इस बीच", "measure": "माप", "mechanic": "मैकेनिक",
    "mechanism": "तंत्र", "medal": "पदक", "media": "मीडिया", "melody": "धुन",
    "memorial": "स्मारक", "mention": "उल्लेख", "menu": "मेन्यू", "merchant": "व्यापारी",
    "mercy": "दया", "messenger": "संदेशवाहक", "meter": "मीटर", "method": "विधि",
    "microphone": "माइक्रोफोन", "midst": "बीच", "mill": "चक्की", "miller": "मिलर",
    "miner": "खनिक", "minister": "मंत्री", "miracle": "चमत्कार", "misery": "दुख",
    "missile": "मिसाइल", "mist": "धुंध", "mister": "मिस्टर", "mistress": "मालकिन",
    "mix": "मिश्रण", "mixture": "मिश्रण", "moan": "कराह", "mob": "भीड़",
    "mode": "मोड", "mole": "तिल", "momma": "माँ", "mommy": "माँ", "monk": "भिक्षु",
    "monkey": "बंदर", "monument": "स्मारक", "moonlight": "चांदनी", "mosquito": "मच्छर",
    "moss": "काई", "motel": "मोटेल", "motive": "उद्देश्य", "motor": "मोटर",
    "motorcycle": "मोटरसाइकिल", "mound": "टीला", "mount": "पहाड़", "mug": "मग",
    "mule": "खच्चर", "mum": "माँ", "murderer": "हत्यारा", "murmur": "कराह",
    "museum": "संग्रहालय", "mushroom": "मशरूम", "musician": "संगीतकार", "mustache": "मूंछ",
    "myth": "मिथक", "nap": "झपकी", "napkin": "नैपकिन", "nation": "राष्ट्र",
    "native": "मूल निवासी", "navy": "नौसेना", "necessity": "आवश्यकता", "necklace": "हार",
    "needle": "सुई", "neon": "नियॉन", "nephew": "भतीजा", "nerve": "नस", "nest": "घोंसला",
    "net": "जाल", "network": "नेटवर्क", "nickname": "उपनाम", "niece": "भतीजी",
    "nightgown": "रात का गाउन", "nightmare": "बुरा सपना", "nipple": "निप्पल",
    "nonsense": "बकवास", "noon": "दोपहर", "nostril": "नथुना", "notebook": "नोटबुक",
    "notice": "नोटिस", "notion": "धारणा", "nun": "नन", "nursery": "नर्सरी",
    "nut": "अखरोट", "objection": "आपत्ति", "obligation": "दायित्व", "observation": "अवलोकन",
    "obsession": "जुनून", "odds": "संभावना", "odor": "गंध", "offense": "अपराध",
    "offer": "प्रस्ताव", "offering": "भेंट", "official": "अधिकारी", "olive": "जैतून",
    "onion": "प्याज", "op": "ऑप", "opera": "ओपेरा", "operator": "ऑपरेटर",
    "opponent": "प्रतिद्वंद्वी", "option": "विकल्प", "orange": "संतरा", "orbit": "कक्षा",
    "orchard": "बाग", "organ": "अंग", "organization": "संगठन", "origin": "मूल",
    "orphan": "अनाथ", "outfit": "पोशाक", "outline": "रूपरेखा", "oven": "ओवन",
    "overcoat": "ओवरकोट", "owl": "उल्लू", "oxygen": "ऑक्सीजन", "pace": "गति",
    "package": "पैकेज", "packet": "पैकेट", "pad": "पैड", "paint": "पेंट",
    "painter": "चित्रकार", "pajamas": "पजामा", "pal": "दोस्त", "palace": "महल",
    "pan": "पैन", "pancake": "पैनकेक", "pane": "शीशा", "panel": "पैनल",
    "pang": "टीस", "panic": "घबराहट", "panties": "पैंटी", "paperwork": "कागजी काम",
    "parade": "परेड", "paradise": "स्वर्ग", "pardon": "माफी", "parlor": "पार्लर",
    "particle": "कण", "pass": "पास", "passage": "मार्ग", "passageway": "गलियारा",
    "passerby": "राहगीर", "passing": "गुजरना", "passport": "पासपोर्ट", "pastor": "पादरी",
    "pasture": "चरागाह", "pat": "थपथपाना", "patience": "धैर्य", "patio": "पाटियो",
    "patrol": "गस्त", "patsy": "पैट्सी", "patty": "पैटी", "pavement": "फुटपाथ",
    "paw": "पंजा", "pay": "वेतन", "payment": "भुगतान", "pea": "मटर", "peach": "आड़ू",
    "peak": "चोटी", "peanut": "मूंगफली", "peasant": "किसान", "pebble": "कंकड़",
    "peer": "साथी", "peg": "खूंटी", "pencil": "पेंसिल", "penguin": "पेंगुइन",
    "penis": "लिंग", "pepper": "काली मिर्च", "perception": "धारणा", "perfection": "पूर्णता",
    "performance": "प्रदर्शन", "perfume": "परफ्यूम", "perimeter": "परिधि",
    "permission": "अनुमति", "personality": "व्यक्तित्व", "personnel": "कर्मचारी",
    "perspective": "परिप्रेक्ष्य", "pet": "पालतू", "petal": "पंखुड़ी", "pew": "बेंच",
    "phase": "चरण", "phenomenon": "घटना", "philosophy": "दर्शन",
    "photographer": "फोटोग्राफर", "phrase": "वाक्यांश", "physician": "चिकित्सक",
    "physics": "भौतिकी", "piano": "पियानो", "pickup": "पिकअप", "picnic": "पिकनिक",
    "pie": "पाई", "pier": "पियर", "pigeon": "कबूतर", "pike": "पाइक", "pilgrim": "तीर्थयात्री",
    "pill": "गोली", "pillar": "स्तंभ", "pin": "पिन", "pirate": "समुद्री डाकू",
    "pit": "गड्ढा", "pitch": "पिच", "pitcher": "पिचर", "pity": "दया", "pizza": "पिज़्ज़ा",
    "plague": "महामारी", "plaid": "प्लेड", "plain": "मैदान", "plank": "तख्ता",
    "plaster": "प्लास्टर", "platter": "थाली", "playground": "खेल का मैदान",
    "plaza": "प्लाजा", "plea": "दलील", "plot": "कथानक", "plum": "आलू बुखारा",
    "plus": "प्लस", "pod": "फली", "podium": "मंच", "poet": "कवि", "poetry": "कविता",
    "poison": "जहर", "poker": "पोकर", "policeman": "पुलिसवाला", "policy": "नीति",
    "politician": "राजनीतिज्ञ", "politics": "राजनीति", "pond": "तालाब",
    "pony": "टट्टू", "ponytail": "पोनीटेल", "pop": "पॉप", "pope": "पोप",
    "poppy": "पोस्त", "population": "जनसंख्या", "pork": "सूअर का मांस",
    "port": "बंदरगाह", "porter": "कुली", "portion": "हिस्सा", "portrait": "चित्र",
    "pose": "मुद्रा", "possession": "कब्जा", "postcard": "पोस्टकार्ड", "poster": "पोस्टर",
    "posture": "मुद्रा", "potato": "आलू", "pouch": "थैली", "pounding": "धड़कन",
    "powder": "पाउडर", "prairie": "प्रेयरी", "praise": "प्रशंसा", "preacher": "उपदेशक",
    "pregnancy": "गर्भावस्था", "preparation": "तैयारी", "prey": "शिकार",
    "principal": "प्रधान", "principle": "सिद्धांत", "print": "छाप", "privacy": "गोपनीयता",
    "privilege": "विशेषाधिकार", "prize": "पुरस्कार", "procedure": "प्रक्रिया",
    "procession": "जुलूस", "producer": "निर्माता", "product": "उत्पाद",
    "production": "उत्पादन", "profession": "पेशा", "profile": "प्रोफाइल",
    "profit": "लाभ", "progress": "प्रगति", "proof": "सबूत", "proposal": "प्रस्ताव",
    "prospect": "संभावना", "protection": "सुरक्षा", "protest": "विरोध",
    "psychiatrist": "मनोचिकित्सक", "pub": "पब", "public": "जनता",
    "publisher": "प्रकाशक", "puddle": "पोखर", "puff": "झोंका", "pull": "खिंचाव",
    "pulse": "नाड़ी", "pump": "पंप", "pumpkin": "कद्दू", "punch": "मुक्का",
    "punishment": "सजा", "punk": "पंक", "pupil": "छात्र", "puppy": "पिल्ला",
    "purchase": "खरीद", "pursuit": "पीछा", "pussy": "बिल्ली", "puzzle": "पहेली",
    "pyramid": "पिरामिड", "quality": "गुणवत्ता", "quilt": "रजाई", "rabbi": "रब्बी",
    "rack": "रैक", "radar": "रडार", "radiation": "विकिरण", "raft": "बेड़ा",
    "rag": "चीथड़ा", "rail": "रेल", "railing": "रेलिंग", "railroad": "रेलवे",
    "rainbow": "इंद्रधनुष", "ram": "भेड़ा", "ramp": "रैंप", "ranch": "रैंच",
    "ranger": "रेंजर", "rank": "पद", "rate": "दर", "raven": "कौआ", "razor": "उस्तरा",
    "reach": "पहुंच", "reader": "पाठक", "realization": "अहसास", "realm": "दायरा",
    "rear": "पिछला", "rebel": "विद्रोही", "receiver": "रिसीवर", "reception": "रिसेप्शन",
    "receptionist": "रिसेप्शनिस्ट", "recipe": "विधि", "recognition": "मान्यता",
    "recorder": "रिकॉर्डर", "recording": "रिकॉर्डिंग", "recovery": "पुनर्प्राप्ति",
    "reed": "सरकंडा", "reference": "संदर्भ", "refrigerator": "फ्रिज",
    "refuge": "शरण", "refugee": "शरणार्थी", "region": "क्षेत्र", "register": "रजिस्टर",
    "regret": "पछतावा", "rein": "लगाम", "relation": "संबंध", "relative": "रिश्तेदार",
    "release": "रिलीज", "religion": "धर्म", "remains": "अवशेष", "remark": "टिप्पणी",
    "reminder": "अनुस्मारक", "remnant": "अवशेष", "rent": "किराया", "rental": "किराया",
    "repair": "मरम्मत", "reply": "जवाब", "republic": "गणतंत्र", "reputation": "प्रतिष्ठा",
    "request": "अनुरोध", "rescue": "बचाव", "resentment": "नाराज़गी",
    "reservation": "आरक्षण", "reserve": "रिजर्व", "residence": "निवास",
    "resident": "निवासी", "resistance": "प्रतिरोध", "resort": "रिसॉर्ट",
    "resource": "संसाधन", "responsibility": "जिम्मेदारी", "retirement": "सेवानिवृत्ति",
    "retreat": "पीछे हटना", "revelation": "रहस्योद्घाटन", "revenge": "बदला",
    "reverend": "रेवरेंड", "review": "समीक्षा", "revolution": "क्रांति",
    "revolver": "रिवॉल्वर", "reward": "इनाम", "rhythm": "लय", "rib": "पसली",
    "ribbon": "रिबन", "rice": "चावल", "rider": "सवार", "ridge": "रिज",
    "rim": "किनारा", "ringing": "घंटी", "riot": "दंगा", "ripple": "लहर",
    "rise": "वृद्धि", "risk": "जोखिम", "ritual": "रिवाज", "roar": "गर्जना",
    "robot": "रोबोट", "rocket": "रॉकेट", "rod": "छड़", "roller": "रोलर",
    "roman": "रोमन", "romance": "रोमांस", "rooftop": "छत", "roommate": "रूममेट",
    "round": "दौर", "route": "मार्ग", "routine": "दिनचर्या", "rover": "रोवर",
    "rubble": "मलबा", "ruby": "रूबी", "rug": "कालीन", "ruin": "खंडहर",
    "rumble": "गड़गड़ाहट", "rumor": "अफवाह", "runner": "धावक", "running": "दौड़",
    "runway": "रनवे", "russian": "रूसी", "sack": "बोरी", "sacrifice": "बलिदान",
    "saddle": "काठी", "sadness": "उदासी", "sage": "ऋषि", "sail": "पाल",
    "sailor": "सailor", "saint": "संत", "salad": "सलाद", "salary": "वेतन",
    "sale": "बिक्री", "sales": "बिक्री", "salesman": "विक्रेता", "salmon": "सैल्मन",
    "salon": "सैलून", "salvation": "मोक्ष", "sample": "नमूना", "sandal": "सैंडल",
    "satellite": "उपग्रह", "satin": "साटन", "satisfaction": "संतुष्टि", "sauce": "सॉस",
    "saucer": "तश्तरी", "sausage": "सॉसेज", "saving": "बचत", "saw": "आरी",
    "saying": "कहावत", "scale": "पैमाना", "scalp": "खोपड़ी", "scan": "स्कैन",
    "scar": "निशान", "scarf": "दुपट्टा", "scenario": "परिदृश्य", "schedule": "समयसारणी",
    "scheme": "योजना", "scholar": "विद्वान", "scientist": "वैज्ञानिक",
    "scissors": "कैंची", "scope": "दायरा", "score": "स्कोर", "scotch": "स्कॉच",
    "scout": "स्काउट", "scrap": "स्क्रैप", "scratch": "खरोंच", "script": "स्क्रिप्ट",
    "sculpture": "मूर्ति", "seal": "सील", "seam": "सीवन", "search": "खोज",
    "sedan": "सिडान", "seed": "बीज", "selection": "चयन", "semester": "सेमेस्टर",
    "senator": "सीनेटर", "sensation": "सनसनी", "sensor": "सेंसर", "sequence": "क्रम",
    "sergeant": "सार्जेंट", "session": "सत्र", "setting": "सेटिंग", "settlement": "समझौता",
    "shack": "झोपड़ी", "shaft": "शाफ्ट", "shake": "हिलाना", "shame": "शर्म",
    "shard": "टुकड़ा", "share": "हिस्सा", "shark": "शार्क", "shawl": "शॉल",
    "shed": "शेड", "sheep": "भेड़", "shelter": "आश्रय", "shepherd": "गड़रिया",
    "shield": "ढाल", "shift": "शिफ्ट", "shiver": "कंपकंपी", "shooting": "शूटिंग",
    "shopping": "खरीदारी", "shorts": "शॉर्ट्स", "shotgun": "शॉटगन", "shout": "चिल्लाना",
    "shovel": "फावड़ा", "shriek": "चीख", "shrug": "कंधे उचकाना", "shuffling": "फेरबदल",
    "shutter": "शटर", "shuttle": "शटल", "sibling": "भाई-बहन", "sickness": "बीमारी",
    "sidebar": "साइडबार", "signature": "हस्ताक्षर", "significance": "महत्व",
    "silhouette": "सिल्हूट", "sin": "पाप", "singer": "गायक", "singing": "गायन",
    "sip": "घूंट", "siren": "सायरन", "sissy": "सिसी", "sitting": "बैठक",
    "skeleton": "कंकाल", "sketch": "स्केच", "ski": "स्की", "slab": "स्लैब",
    "slack": "ढील", "slate": "स्लेट", "slave": "गुलाम", "sleeping": "सोना",
    "slice": "टुकड़ा", "slide": "स्लाइड", "slip": "स्लिप", "slipper": "चप्पल",
    "slope": "ढलान", "slot": "स्लॉट", "snack": "नाश्ता", "sneakers": "स्नीकर्स",
    "soap": "साबुन", "sob": "सिसकी", "soccer": "फुटबॉल", "sock": "मोज़ा",
    "socket": "सॉकेट", "soda": "सोडा", "software": "सॉफ्टवेयर", "soil": "मिट्टी",
    "sole": "तलवा", "solitude": "एकांत", "solution": "समाधान", "sorrow": "दुख",
    "soup": "सूप", "spark": "चिंगारी", "sparrow": "गौरैया", "speaker": "स्पीकर",
    "spear": "भाला", "species": "प्रजाति", "specimen": "नमूना", "spectacle": "तमाशा",
    "spell": "जादू", "sphere": "गोला", "spice": "मसाला", "spider": "मकड़ी",
    "spike": "स्पाइक", "spine": "रीढ़", "spit": "थूक", "splash": "छपाक",
    "spoon": "चम्मच", "spray": "स्प्रे", "spread": "फैलाव", "spy": "जासूस",
    "squad": "टीम", "squirrel": "गिलहरी", "stagger": "लड़खड़ाना", "stain": "दाग",
    "staircase": "सीढ़ी", "stairway": "सीढ़ी", "stairwell": "सीढ़ी", "stake": "दांव",
    "stall": "स्टॉल", "stamp": "स्टैंप", "standard": "मानक", "standing": "खड़ा",
    "stare": "घूरना", "starling": "स्टार्लिंग", "statement": "बयान", "statue": "मूर्ति",
    "status": "स्थिति", "stay": "ठहराव", "steak": "स्टेक", "steam": "भाप",
    "steering": "स्टीयरिंग", "stem": "तना", "stench": "बदबू", "stereo": "स्टीरियो",
    "stern": "कड़ा", "stew": "स्ट्यू", "stillness": "शांति", "stock": "स्टॉक",
    "stocking": "मोज़ा", "stool": "स्टूल", "storage": "भंडारण", "stove": "चूल्हा",
    "strain": "तनाव", "strand": "तार", "strap": "पट्टा", "strategy": "रणनीति",
    "straw": "पुआल", "strawberry": "स्ट्रॉबेरी", "streak": "धारी", "stress": "तनाव",
    "stretch": "खिंचाव", "stride": "लंबा कदम", "strike": "हड़ताल", "strip": "पट्टी",
    "stripe": "धारी", "stroke": "स्ट्रोक", "structure": "संरचना", "struggle": "संघर्ष",
    "studio": "स्टूडियो", "stump": "स्टंप", "substance": "पदार्थ", "suburb": "उपनगर",
    "subway": "मेट्रो", "success": "सफलता", "suffering": "पीड़ा", "suggestion": "सुझाव",
    "suicide": "आत्महत्या", "suite": "सूट", "sum": "योग", "sunglasses": "धूप का चश्मा",
    "sunrise": "सूर्योदय", "sunset": "सूर्यास्त", "sunshine": "धूप",
    "supermarket": "सुपरमार्केट", "supervisor": "पर्यवेक्षक", "supper": "रात का खाना",
    "support": "समर्थन", "surf": "सर्फ", "surge": "लहर", "surgeon": "सर्जन",
    "surgery": "सर्जरी", "surroundings": "परिवेश", "surveillance": "निगरानी",
    "survival": "उत्तरजीविता", "survivor": "उत्तरजीवी", "suspect": "संदिग्ध",
    "suspicion": "संदेह", "swallow": "निगलना", "swamp": "दलदल", "swan": "हंस",
    "sweater": "स्वेटर", "sweatshirt": "स्वेटशर्ट", "sweep": "झाड़ू", "sweet": "मिठाई",
    "sweetheart": "प्रिय", "sweetie": "प्रिय", "swell": "सूजन", "swimming": "तैराकी",
    "swing": "झूला", "switch": "स्विच", "syllable": "अक्षर", "symbol": "प्रतीक",
    "sympathy": "सहानुभूति", "symptom": "लक्षण", "tag": "टैग", "talent": "प्रतिभा",
    "talking": "बातचीत", "tan": "तन", "tangle": "उलझन", "tap": "नल",
    "target": "लक्ष्य", "tattoo": "टैटू", "tavern": "मधुशाला", "tax": "कर",
    "taxi": "टैक्सी", "teaching": "शिक्षण", "tech": "टेक", "technician": "तकनीशियन",
    "technique": "तकनीक", "technology": "तकनीक", "teen": "किशोर",
    "teenager": "किशोर", "telescope": "दूरबीन", "temper": "गुस्सा",
    "temperature": "तापमान", "tennis": "टेनिस", "tension": "तनाव", "tentacle": "जाल",
    "terminal": "टर्मिनल", "terrace": "छत", "terrain": "इलाका", "territory": "क्षेत्र",
    "terror": "आतंक", "terrorist": "आतंकवादी", "testimony": "गवाही", "text": "पाठ",
    "thanksgiving": "थैंक्सगिविंग", "theme": "विषय", "therapist": "चिकित्सक",
    "therapy": "चिकित्सा", "thief": "चोर", "think": "सोच", "thorn": "कांटा",
    "thread": "धागा", "threat": "धमकी", "threshold": "दहलीज", "thrill": "रोमांच",
    "throne": "सिंहासन", "thud": "धमाका", "thug": "गुंडा", "thunder": "बिजली",
    "tide": "ज्वार", "tiger": "बाघ", "til": "तिल", "tile": "टाइल", "timing": "समय",
    "tin": "टिन", "tissue": "टिशू", "title": "शीर्षक", "toast": "टोस्ट",
    "tobacco": "तंबाकू", "tomato": "टमाटर", "tomb": "कब्र", "topic": "विषय",
    "torch": "मशाल", "torso": "धड़", "torture": "यातना", "tour": "दौरा",
    "tourist": "पर्यटक", "toy": "खिलौना", "trace": "निशान", "tractor": "ट्रैक्टर",
    "trade": "व्यापार", "tradition": "परंपरा", "tragedy": "त्रासदी", "trailer": "ट्रेलर",
    "training": "प्रशिक्षण", "transfer": "ट्रांसफर", "translation": "अनुवाद",
    "translator": "अनुवादक", "transmission": "ट्रांसमिशन", "transport": "परिवहन",
    "trap": "जाल", "trash": "कचरा", "travel": "यात्रा", "traveler": "यात्री",
    "treasure": "खजाना", "treat": "इलाज", "treatment": "उपचार", "trench": "खाई",
    "trial": "मुकदमा", "triangle": "त्रिभुज", "tribe": "जनजाति", "trigger": "ट्रिगर",
    "triumph": "जीत", "troll": "ट्रॉल", "troop": "सैन्य दल", "trooper": "सैनिक",
    "trophy": "ट्रॉफी", "trousers": "पतलून", "trout": "ट्राउट", "trust": "विश्वास",
    "try": "कोशिश", "tub": "टब", "tug": "खिंचाव", "tune": "धुन", "tunic": "कुर्ता",
    "turkey": "टर्की", "turning": "मोड़", "turtle": "कछुआ", "twig": "टहनी",
    "twilight": "गोधूलि", "twist": "मोड़", "umbrella": "छाता", "understanding": "समझ",
    "underwear": "अंडरवियर", "union": "संघ", "up": "ऊपर", "urge": "आग्रह",
    "urgency": "जरूरत", "vacation": "छुट्टी", "vacuum": "वैक्यूम", "valentine": "वेलेंटाइन",
    "value": "मूल्य", "vampire": "वैम्पायर", "vanity": "घमंड", "variety": "विविधता",
    "vase": "फूलदान", "vault": "तहखाना", "vegetable": "सब्जी", "veil": "नकाब",
    "vein": "नस", "velvet": "मखमल", "vent": "वेंट", "verge": "कगार", "verse": "पद्य",
    "vessel": "पात्र", "vest": "वेस्ट", "vet": "पशु चिकित्सक", "victor": "विजेता",
    "victory": "जीत", "villager": "ग्रामीण", "vine": "बेल", "violence": "हिंसा",
    "violet": "बैंगनी", "violin": "वायलिन", "virgin": "कुंवारी", "virtue": "गुण",
    "virus": "वायरस", "vodka": "वोडका", "void": "शून्य", "volcano": "ज्वालामुखी",
    "volume": "आयतन", "volunteer": "स्वयंसेवक", "vote": "वोट", "vow": "व्रत",
    "voyage": "समुद्र यात्रा", "wad": "गड्डी", "wait": "इंतजार", "waiter": "वेटर",
    "waiting": "इंतजार", "waitress": "वेट्रेस", "wake": "जागना", "walker": "वॉकर",
    "walking": "चलना", "walkway": "पैदल मार्ग", "wallet": "बटुआ", "ward": "वार्ड",
    "warden": "वार्डन", "wardrobe": "अलमारी", "warehouse": "गोदाम", "warmth": "गर्मी",
    "warrior": "योद्धा", "wash": "धोना", "waste": "बर्बादी", "wax": "मोम",
    "weakness": "कमजोरी", "wealth": "संपत्ति", "web": "जाल", "weed": "घास",
    "welcome": "स्वागत", "wheat": "गेहूं", "wheelchair": "व्हीलचेयर", "whip": "कोड़ा",
    "whiskey": "व्हिस्की", "whistle": "सीटी", "whole": "पूरा", "whore": "वेश्या",
    "widow": "विधवा", "wig": "विग", "wilderness": "जंगल", "willow": "विलो",
    "windshield": "विंडशील्ड", "wink": "पलक", "winner": "विजेता", "wisdom": "बुद्धि",
    "wish": "इच्छा", "wit": "बुद्धि", "witch": "चुड़ैल", "witness": "गवाह",
    "wizard": "जादूगर", "wool": "ऊन", "workshop": "कार्यशाला", "worm": "कीड़ा",
    "worry": "चिंता", "worth": "मूल्य", "wreck": "मलबा", "wren": "रेन",
    "wrinkle": "झुर्री", "zone": "क्षेत्र", "zoo": "चिड़ियाघर",
}
# Fix typo
EXTRA["sailor"] = "सैलर"
out_path = os.path.join(BASE, "en_hi_extra.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(EXTRA, f, ensure_ascii=False, indent=0)
print(f"Wrote {out_path} with {len(EXTRA)} entries")
